name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Búsqueda extrema de gradlew
        run: |
          echo "Buscando gradlew..."
          find . -name "gradlew"
          GRADLEW_PATH=$(find . -name gradlew | head -n 1)
          
          if [ -z "$GRADLEW_PATH" ]; then
            echo "¡ERROR: No se encontró gradlew en ninguna parte!"
            exit 1
          fi
          
          echo "Encontrado en: $GRADLEW_PATH"
          DIR=$(dirname "$GRADLEW_PATH")
          cd "$DIR"
          chmod +x gradlew
          ./gradlew assembleDebug
          
          # Copiar el archivo encontrado a un lugar donde el último paso lo vea
          mkdir -p $GITHUB_WORKSPACE/output
          find . -name "app-debug.apk" -exec cp {} $GITHUB_WORKSPACE/output/ \;

      - name: Subir el APK Generado
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: output/app-debug.apk
