name: Compilar APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Gradle Requerido
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '9.3.1'

      - name: Buscar Proyecto y Compilar APK
        run: |
          # Buscamos dónde está el archivo de configuración
          CONFIG_PATH=$(find . -name "build.gradle*" | head -n 1)
          if [ -z "$CONFIG_PATH" ]; then
            echo "¡ERROR: No se encontró ningún archivo build.gradle!"
            exit 1
          fi
          
          # Nos metemos adentro de esa carpeta
          DIR=$(dirname "$CONFIG_PATH")
          echo "Proyecto encontrado en la carpeta: $DIR"
          cd "$DIR"
          
          # Fabricamos de prepo los archivos .env para que no tire error
          touch .env.example
          touch .env
          echo "Archivos .env configurados a la fuerza."
          
          # Compilamos directamente con Gradle
          gradle assembleDebug
          
          # Guardamos el APK en un lugar seguro
          mkdir -p $GITHUB_WORKSPACE/output
          find . -name "app-debug.apk" -exec cp {} $GITHUB_WORKSPACE/output/ \;

      - name: Subir el APK Generado
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: output/app-debug.apk
          
